#!/bin/sh

backup_conf() {
  apm list -b --installed > packages.txt
}

restore_packages() {
  apm install --packages-file packages.txt
}

usage() {
  echo "Usage: ${0} {install|save-deps}"
}

case "$1" in
  "save-deps")
    backup_conf
  ;;

  "install")
    restore_packages
  ;;

  *)
    usage
  ;;
esac
